# Generated by Django 4.2.4 on 2023-08-06 09:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('date_modified', models.DateField(default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human', models.TextField()),
                ('ai', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('date_modified', models.DateField(default=datetime.datetime.now)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.sessions')),
            ],
        ),
    ]
